#!/usr/bin/env ruby

source "https://api.berkshelf.com"

cookbook 'appsindo',
   :git => 'https://github.com/appsindo/chef-appsindo.git'

cookbook "mongodb",
  :git => "https://github.com/chef-brigade/mongodb-cookbook.git",
  :ref => "master"